export const districts = [
  { id: 0, name: "Select District", unavailable: false },
  { id: 18, name: "Anuradhapura", unavailable: false },
  { id: 20, name: "Badulla", unavailable: false },
  { id: 14, name: "Batticaloa", unavailable: false },
  { id: 1, name: "Colombo", unavailable: false },
  { id: 7, name: "Galle", unavailable: false },
  { id: 2, name: "Gampaha", unavailable: false },
  { id: 8, name: "Hambantota", unavailable: false },
  { id: 9, name: "Jaffna", unavailable: false },
  { id: 3, name: "Kalutara", unavailable: false },
  { id: 4, name: "Kandy", unavailable: false },
  { id: 23, name: "Kegalle", unavailable: false },
  { id: 10, name: "Kilinochchi", unavailable: false },
  { id: 16, name: "Kurunegala", unavailable: false },
  { id: 5, name: "Matale", unavailable: false },
  { id: 21, name: "Moneragala", unavailable: false },
  { id: 13, name: "Mullaitivu", unavailable: false },
  { id: 6, name: "Nuwara Eliya", unavailable: false },
  { id: 17, name: "Puttalam", unavailable: false },
  { id: 19, name: "Polonnaruwa", unavailable: false },
  { id: 22, name: "Ratnapura", unavailable: false },
  { id: 15, name: "Trincomalee", unavailable: false },
  { id: 12, name: "Vavuniya", unavailable: false },
];
